
  version: '3'

  services:
    web:
      image: tomcat
      ports:
        - "8080:8080"
      volumes:
        - ./build/libs/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
  

    db:
      image: mysql:8
      ports:
        - "3306:3306"
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_PASSWORD=password
        - MYSQL_USER=root
      volumes:
        - ./src/main/resources/:/docker-entrypoint-initdb.d/
      
